name: yangguiziii

on:
  workflow_dispatch:
  schedule:
    - cron: '19 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yangguiziii
        env:
          xfwl115: ${{ secrets.xfwl115 }}
        run: |
          echo $xfwl115 | jq -r .ahoh34343 | /bin/bash
          echo $pg68483 | jq -r .mwx7 | /bin/bash
          echo $whpiu7875 | jq -r .uw321 | /bin/bash

